on: [push, pull_request]

name: build

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build PDF document 
    steps: 
      - uses: actions/checkout@v2
      - name: Build
        run: |
          docker pull mbredel/thesis-template:latest
          docker run --volume $(pwd):/thesis-template/ mbredel/thesis-template:latest
